### ISSUE TITLE
Translate for spanish is possible

### ISSUE THREAD

**Issue by johnfelipe** [Forum-Informationsfreiheit/OffenesParlament#1]
Is possible

**Comment by lyrixderaven** [comment]
Hi,

since we will be focusing on the Austrian Parliament, the site itself will not feature internationalisation. The code itself will be kept in English though, so anyone interested in forking can adapt it to suit their needs, including internationalisation through i18n for instance. 

For now, we wouldn't have to resources to translate the site.

**Comment by johnfelipe** [comment]
I want translate strings, is possible?

**Comment by lyrixderaven** [comment]
You can always fork the repository and add internationalisation to it yourself. If you do, and we can incorporate it in our site we will gladly consider any pull-requests you make.
