### ISSUE TITLE
Search results: Aktualisierungs-Date 01.01.1970

### ISSUE THREAD

**Issue by hutershvili** [Forum-Informationsfreiheit/OffenesParlament#69]
I searched for "hypo" and got several search results with the date 01.01.1970, which does not appear to be correct. maybe we can fix this, or if no date is available, then say "nicht verfügbar" or leave it blank?

http://offenesparlament.at/suche?llps=XXV&q=hypo

**Comment by lyrixderaven** [comment]
Well, i looked into it, and i can't change that in the backend. This is a default value i'm setting for the timestamp value in the index, and if I remove it, we end up with lots of errors whenever there's a connection problem while scraping so that the timestamp isn't set (or can't be set). As a safety precaution, I'd rather not remove this from the indexing procedure. 

I assume it would be possible to filter this out in the frontend though, maybe Ben can check this out? Since we're not scraping llps for laws further back than XX (1996) anyways, it's safe to assume that any date that comes up as 1.1.1970 can be shown as empty.
