### ISSUE TITLE
Search results: links broken

### ISSUE THREAD

**Issue by hutershvili** [Forum-Informationsfreiheit/OffenesParlament#70]
I searched for "hypo", all the links to search results appear to be broken

http://offenesparlament.at/suche?llps=XXV&q=hypo

**Comment by fin** [comment]
i reproduced this.
![image](https://cloud.githubusercontent.com/assets/25808/14133895/43ec2fce-f653-11e5-9d1d-3b863bdc5550.png)

the issue seems to be a that there are two different types of parl_id formatting in the database, and `offenesparlament/views/base_views.py:gesetz_detail` only implements the "parl_id in brackets" one.
we should probably normalize this before it enters the database?

![image](https://cloud.githubusercontent.com/assets/25808/14133906/52b93ca4-f653-11e5-877d-c3cc1b1bb0c9.png)

**Comment by fin** [comment]
@benfreu OTOH, looks like that's also the wrong content type for that view. could you double-check this?
