### ISSUE TITLE
Personen: show most current party affiliation

### ISSUE THREAD

**Issue by hutershvili** [Forum-Informationsfreiheit/OffenesParlament#71]
It would be great if we could display the most current party affiliation of an Abgeordnete(r) at http://offenesparlament.at/personen/XXV/ and the top of their profile.

For example: Marcus Franz has been a member of Team Stronach, of ÖVP and now is OK. The top of his profile lists him as Team Stronach
http://offenesparlament.at/personen/PAD_83141/Franz-Marcus-Dr-/

**Comment by lyrixderaven** [comment]
This is a scraping issue, sadly a very complicated one, since we are getting the mandates from two different sources (person list and detail page); the detail page isn't always scrapeable (since the dates there aren't always following a norm), and the list doesn't show the exact dates of when the mandate starts or ends. I'll look into it, but it will take some time.

**Comment by lyrixderaven** [comment]
Not a perfect fix, but at least it helps with, for instance, Marcus Franz. Check the commit message for rollout instructions.
